name: C/C++ CI

on: [push]

jobs:
  build:
    name: ${{ matrix.os }} | ${{ matrix.compiler }} 
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        compiler: [clang, gcc]
    steps:
    - uses: actions/checkout@v1      
    - name: make test (${{ matrix.compiler }})
      run: make test CC=${{ matrix.compiler }}
  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1    
      - name: make coverage (clang)
        run: make CC=clang && make coverage
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./build/test/coverage.info  
